# Generated by Django 3.0 on 2019-12-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='channel_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
