# Generated by Django 3.0 on 2019-12-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191224_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='disliked',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='liked',
            field=models.CharField(default='', max_length=255),
        ),
    ]
