# Generated by Django 3.0 on 2020-01-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200109_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
