# Generated by Django 3.0 on 2020-01-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200107_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
