# Generated by Django 3.0 on 2019-12-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='channel_model',
            fields=[
                ('channel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='channel_logo')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('followers', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('video_id', models.CharField(default='', max_length=100, null=True)),
                ('playlist', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
