# Generated by Django 3.0 on 2019-12-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_channel_model_video_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel_model',
            name='video_ids',
        ),
    ]
