# Generated by Django 3.0 on 2020-01-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_remove_channel_model_video_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_model',
            name='courses_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
