# Generated by Django 3.0 on 2020-01-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_course_course_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, max_length=100, null=True),
        ),
    ]
