# Generated by Django 3.0 on 2020-01-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_auto_20200113_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
