# Generated by Django 3.0 on 2020-01-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_auto_20200113_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='channel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
