# Generated by Django 3.0 on 2020-01-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_course_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_session',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
