# Generated by Django 3.0 on 2020-01-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0011_auto_20200113_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
