# Generated by Django 3.0 on 2020-01-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0012_auto_20200113_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirement',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
