# Generated by Django 3.0 on 2019-12-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videous')),
                ('length_of_video', models.IntegerField()),
                ('url', models.URLField()),
                ('thumb_image', models.ImageField(upload_to='thumb_image')),
                ('channel_id', models.CharField(max_length=100, null=True)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('playlist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('is_downloadable', models.BooleanField()),
                ('is_sharable', models.BooleanField()),
            ],
        ),
    ]
