# Generated by Django 3.0 on 2019-12-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20191224_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_class',
            old_name='channel_id',
            new_name='video_id',
        ),
    ]
