# Generated by Django 3.0 on 2019-12-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20191224_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_class',
            name='channel_id',
            field=models.IntegerField(null=True),
        ),
    ]
