# Generated by Django 3.0 on 2019-12-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_class_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_class',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
