# Generated by Django 3.0 on 2019-12-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_class_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_class',
            name='video_id',
        ),
        migrations.AddField(
            model_name='video_class',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
