# Generated by Django 3.0 on 2020-01-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20191226_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_class',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
