# Generated by Django 3.0 on 2020-01-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_video_class_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_class',
            name='length_of_video',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video_class',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
