# Generated by Django 3.0 on 2020-01-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20200107_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('requirement', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('categary', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(max_length=100)),
                ('session_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.course_session')),
            ],
        ),
    ]
