# Generated by Django 3.0 on 2020-01-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_course_course_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='course_session',
        ),
    ]
